= iText

== Allgemeine Informationen

iText ist eine Library, mit der man dynamisch, PDF Dateien aus Java Applikationen erstellen kann.

== Maven Dependency

    <dependency>
        <groupId>com.itextpdf<groupId>
        <artifactId>itextpdf<artifactId>
        <version>5.5.13<version>
    <dependency>

== Hello World Beispiel

    import java.io.FileNotFoundException;
    import java.io.FileOutputStream;
    import com.itextpdf.text.Document;
    import com.itextpdf.text.DocumentException;
    import com.itextpdf.text.Paragraph;
    import com.itextpdf.text.pdf.PdfWriter;

    public class JavaPdfHelloWorld {
        public static void main(String[] args) {
            Document document = new Document();
            try {
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(&quot;HelloWorld.pdf&quot;));
                document.open();
                document.add(new Paragraph(&quot;A Hello World PDF document.&quot;));
                document.close();
                writer.close();
            } catch (DocumentException e) {
                e.printStackTrace();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

Mit diesem Beispiel wird eine einfache PDF Datei mit dem Inhalt "A Hello World PDF document." erstellt.