== Pflichtenheft "Was mache ich"


=== Ausgangssituation

Das unabhängige Familienunternehmen namens Ostwind welches
moderne Wind- und Solarparks europaweit projektiert und errichtet
hat Ihre Stammorte in Frankreich und Deutschland verteilt.

In der Vergangenheit haben sie schon 603 Windkraftanlagen mit 1085
Megawatt Leistung geplant, gebaut und ans Netz gebracht. Energiekonsumenten welche
Wert auf ökonomische Energie legen, können sich diesen Wunsch bei Ostwind
erfüllen lassen.

=== Istzustand



=== Problemstellung

In der Vergangenheit kam es öfters vor, dass durch motivierte
Wanderer die Vegetation verschmutzt und zerstört wurde,
indem sie unmarkierte/unoffizielle Wege nahmen.
Um die Bäume und das Umfeld in solchen Gebieten in Zukunft
zu schützen wird eine Software entwickelt, die als Profit
für die Einwohner wegen des darauffolgenden Tourismus dient.

=== Aufgabenstellung
==== Funktionale Anforderungen

[plantuml,wireframe,png]
----
@startsalt
{
Name         | "                 "
Modifiers:   | { (X) public | () default | () private | () protected
	            [] abstract | [] final   | [] static }
Superclass:  | { "java.lang.Object " | [Browse...] }
}
@endsalt
----
==== Nichtfunktionale Anforderungen (NFA)
=== Ziele
=== Mengengerüst
=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber

== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"

=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startuml
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@enduml
----

* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]