@startuml
left to right direction
class Kontrollstelle {
    * Long: id
    + String: name
    + Double: latitudeCoordinate
    + Double: longitudeCoordinate
    ~ Route: route
}

class Route {
    * Long: id
    + String: name
    + Double: length
}

class Wanderung {
    * Long: id
    + Date: dateOfJourney
    - List<Hiker>: groupOfHikers
    - Route: route
    - Hiker: hiker
}

class Wanderer {
    * Long: id
    + String: firstName
    + String: lastName
}

class Bild {
    * Long: id
    + String: fileName
    + byte[]: imageData
    ~ ControlPoint: controlPoint
    ~ Hike: hike
}

Bild "*" --> "1" Kontrollstelle

Kontrollstelle "*" --> "1" Route

Route "*" - "*" Wanderer
(Route, Wanderer) .. Wanderung


Wanderung "1" <-- "*" Bild
@enduml